# Generated by Django 6.0.3 on 2026-03-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('research', 'Research'), ('licensing', 'Licensing'), ('policy_regulations', 'Policy and Regulation'), ('standards', 'Standards'), ('numbering', 'Numbering'), ('billing', 'Billing'), ('internet_speed', 'Internet Speed')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
